sudo: false

language: python
python:
  - "3.4_with_system_site_packages"
  - "3.5"
  - "3.6"
  - nightly
# command to install dependencies

before_install:
  - env
  - echo "Python diagnostic Information"
  - pyenv --version
  - pyenv versions
  - pyenv global
  - 'which -a python'
  - python --version
  - python-config --includes
  - python-config --libs
  - python-config --ldflags
  - pip --version
  - ls -l ~/virtualenv
  - sudo apt-get update -qq
  - sudo apt-get install -qq python-dbus python3-dbus python3-gi libdbus-glib-1-dev libdbus-1-3 libdbus-1-dev

install:
  - pip install .
  - pip install blinker
  - pip install flask_testing
  - pip install codecov
  - pip install nose-cov

cache:
  - pip
  - apt

addons:
  apt:
    packages:
      - dbus
      - libdbus-1-dev
      - libdbus-glib-1-dev

# command to run tests
script:
  - nosetests --nocapture --with-cov --cov-config .coveragerc

after_success:
- codecov

env:
  global:
    - 'PYTHON_LIBS="-L$(python-config --prefix)/lib $(python-config --libs)"'
    - PY_ENABLE_SHARD=0
