language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - nightly
# command to install dependencies
install:
  - pip install .
  - pip install blinker
  - pip install flask_testing
  - pip install codecov
  - pip install nose-cov
  - pip install nose-exclude
# command to run tests
script:
  - export TESTING=True
  - nosetests --exclude-test=test_spotify.WindowsTests --nocapture --with-cov --cov-config .coveragerc

after_success:
- codecov

deploy:
  provider: pypi
  user: aadibajpai
  password:
    secure: a2+fH9kTBJXZWquLEuCygM0C5tealnmQ8yRc0DZ1iDjtrO0Gt62Yio2klwe/v7JsZK+eh4xNX5Su8u9gtEhdYg7Tptdlakc0sGRFooRxUGITlDrglPn9aYCXMwRQpCXtj4c0JSIJRPoKw/FP5QqyL30pO5uHoCU3hAqVaI1qDrqyxhETOt3bpH7eVe74LO6RVy8s6mMxY8gAC4b7YmDYBaNMJ4uSt/Ihi4tfzGNZa1pi/J27ajC6h376wRSPlml/2a1kMoH/F+3LyW3/fkSRww/3wD6+0ejs8pRVoyqrHoxsK0wb3Ic9UY9Q4I61BMwUdIJqOjurtob6afSpK4hCcE7excCWRNDQzyS11gD1FiXXpRZgCT3YMk9gd3mO7Js7XxHRPWyB9kaEKOrO7kTQGDQJbQlXC3X01eZxVFJntzo6SVfF9QtKeOg3/vrvKK+j2OWKQvuTQ8ONmdPxZXl//uHxk8jYHD3vmogaLKgLw07c3xRj7SikvUY5RMvqfi5vsamAL+4kPxkY8TbUmjpFnkdZTrERsQjc0so12/mhbCuM9RSUqFvHz9cd9sXOHSXsesHJerKs9ajGr2nKVHVTl6rgeaQYeW2tt5iMgB+uD6lkT5S9pw7Zl6FP7VWtVUp8bT/BrUtWbKeWm44tNX09hItkl/i4ByzvI8+dJSh4aEM=
  skip_existing: true
  distributions: "sdist bdist_wheel"
  on:
    tags: true