language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - nightly
# command to install dependencies
install:
  - pip install .
  - pip install codecov
  - pip install coverage

after_success:
  - codecov
# command to run tests
script: 
  - python -m unittest swaglyrics/tests.py
  - coverage run tests.py